// pkgs/experimental/swarmakit/libs/vue/src/components/Carousel/Carousel.vue
<template>
  <div class="carousel" role="region" aria-label="Image carousel">
    <div class="carousel-inner" @mouseenter="pause" @mouseleave="autoPlay">
      <div
        v-for="(slide, index) in slides"
        :key="index"
        class="carousel-item"
        :class="{ active: index === currentIndex }"
        :aria-hidden="index !== currentIndex"
      >
        <img :src="slide.src" :alt="slide.alt" />
      </div>
    </div>
    <button class="carousel-control prev" @click="prevSlide" aria-label="Previous slide">‹</button>
    <button class="carousel-control next" @click="nextSlide" aria-label="Next slide">›</button>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, onMounted, onUnmounted } from 'vue';

export default defineComponent({
  name: 'Carousel',
  props: {
    slides: {
      type: Array as () => { src: string; alt: string }[],
      required: true,
    },
    interval: {
      type: Number,
      default: 3000,
    },
  },
  setup(props) {
    const currentIndex = ref(0);
    let intervalId: number | null = null;

    const nextSlide = () => {
      currentIndex.value = (currentIndex.value + 1) % props.slides.length;
    };

    const prevSlide = () => {
      currentIndex.value = (currentIndex.value - 1 + props.slides.length) % props.slides.length;
    };

    const autoPlay = () => {
      intervalId = window.setInterval(nextSlide, props.interval);
    };

    const pause = () => {
      if (intervalId !== null) {
        clearInterval(intervalId);
        intervalId = null;
      }
    };

    onMounted(autoPlay);
    onUnmounted(pause);

    return {
      currentIndex,
      nextSlide,
      prevSlide,
      autoPlay,
      pause,
    };
  },
});
</script>

<style scoped lang="css">
.carousel {
  position: relative;
  overflow: hidden;
  width: 100%;
  background-color: var(--carousel-bg-color);
}

.carousel-inner {
  display: flex;
  transition: transform 0.5s ease;
}

.carousel-item {
  min-width: 100%;
  transition: opacity 0.5s ease;
  opacity: 0;
  position: absolute;
  top: 0;
  left: 0;
}

.carousel-item.active {
  opacity: 1;
  position: relative;
}

.carousel-control {
  position: absolute;
  top: 50%;
  transform: translateY(-50%);
  background-color: var(--control-bg-color);
  color: var(--control-text-color);
  border: none;
  font-size: 2rem;
  cursor: pointer;
  padding: 0.5rem;
}

.carousel-control.prev {
  left: 10px;
}

.carousel-control.next {
  right: 10px;
}
</style>

// pkgs/experimental/swarmakit/libs/svelte/src/components/Carousel/Carousel.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { writable,get } from 'svelte/store';

  export let images: string[] = [];
  export let autoPlay: boolean = false;
  export let autoPlayInterval: number = 3000;

  let currentIndex = 0;
  let intervalId: NodeJS.Timeout;
  const isHovered = writable(false);

  const nextSlide = () => {
    currentIndex = (currentIndex + 1) % images.length;
  };

  const prevSlide = () => {
    currentIndex = (currentIndex - 1 + images.length) % images.length;
  };

  const startAutoPlay = () => {
    if (autoPlay && images.length > 1) {
      intervalId = setInterval(() => {
        if (!get(isHovered)) {
          nextSlide();
        }
      }, autoPlayInterval);
    }
  };

  const stopAutoPlay = () => {
    clearInterval(intervalId);
  };

  onMount(() => {
    startAutoPlay();
    return () => stopAutoPlay();
  });
</script>

<div class="carousel" role="region" aria-label="Image Carousel" on:mouseenter={() => isHovered.set(true)} on:mouseleave={() => isHovered.set(false)}>
  <button on:click={prevSlide} on:keydown={(e) => e.key === 'Enter' && prevSlide()} aria-label="Previous slide">&#10094;</button>
  
  {#each images as image, index}
    <img src={image} alt={`Slide ${index + 1}`} class:selected={index === currentIndex} />
  {/each}
  
  <button on:click={nextSlide} on:keydown={(e) => e.key === 'Enter' && nextSlide()} aria-label="Next slide">&#10095;</button>
</div>

<style lang="css">
  @import './Carousel.css';
</style>
