// pkgs/experimental/swarmakit/libs/svelte/src/components/ContextualList/ContextualList.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  
  export let items: { id: number; label: string; actionTriggered?: boolean }[] = [];
  export let visible: boolean = true;
  
  const dispatch = createEventDispatcher();

  const triggerAction = (item: { id: number; label: string; actionTriggered?: boolean }) => {
    item.actionTriggered = true;
    dispatch('action', { item });
  };

  const dismiss = () => {
    visible = false;
    dispatch('dismiss');
  };
</script>

{#if visible}
  <ul class="contextual-list">
    {#each items as item (item.id)}
      <li class="list-item {item.actionTriggered ? 'action-triggered' : ''}">
        {item.label}
        <button on:click={() => triggerAction(item)}>Trigger Action</button>
      </li>
    {/each}
    <li>
      <button on:click={dismiss}>Dismiss</button>
    </li>
  </ul>
{/if}

<style lang="css">
  @import './ContextualList.css';
</style>

// pkgs/experimental/swarmakit/libs/vue/src/components/ContextualList/ContextualList.vue
<template>
  <div class="contextual-list" role="list">
    <div
      v-for="(item, index) in items"
      :key="index"
      class="list-item"
      :class="{ actionTriggered: item.actionTriggered, dismissed: item.dismissed }"
    >
      <span>{{ item.label }}</span>
      <button @click="triggerAction(index)">Action</button>
      <button @click="dismissItem(index)">Dismiss</button>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

interface ListItem {
  label: string;
  actionTriggered: boolean;
  dismissed: boolean;
}

export default defineComponent({
  name: 'ContextualList',
  props: {
    items: {
      type: Array as () => ListItem[],
      required: true,
    },
  },
  setup(props) {
    const triggerAction = (index: number) => {
      props.items[index].actionTriggered = true;
    };

    const dismissItem = (index: number) => {
      props.items[index].dismissed = true;
    };

    return { triggerAction, dismissItem };
  },
});
</script>

<style scoped lang="css">
.contextual-list {
  padding: 0;
}

.list-item {
  display: flex;
  justify-content: space-between;
  margin-bottom: var(--list-item-margin-bottom, 10px);
  padding: var(--list-item-padding, 10px);
  background-color: var(--list-item-background, #fff);
  border: var(--list-item-border, 1px solid #ccc);
}

.list-item.actionTriggered {
  background-color: var(--action-triggered-background, #e0f7fa);
}

.list-item.dismissed {
  display: none;
}
</style>
