// pkgs/experimental/swarmakit/libs/sveltekit/src/components/DatePicker/DatePicker.svelte
<script lang="ts">
  export let date: string = '';
  export let startDate: string = '';
  export let endDate: string = '';
  export let time: string = '';
  export let mode: 'single' | 'range' | 'time' = 'single';

  function handleDateChange(event: Event) {
    date = (event.target as HTMLInputElement).value;
  }

  function handleStartDateChange(event: Event) {
    startDate = (event.target as HTMLInputElement).value;
  }

  function handleEndDateChange(event: Event) {
    endDate = (event.target as HTMLInputElement).value;
  }

  function handleTimeChange(event: Event) {
    time = (event.target as HTMLInputElement).value;
  }
</script>

<div class="date-picker-container">
  {#if mode === 'single'}
    <input
      type="date"
      bind:value={date}
      aria-label="Select Date"
      on:input={handleDateChange}
    />
  {:else if mode === 'range'}
    <input
      type="date"
      bind:value={startDate}
      aria-label="Select Start Date"
      on:input={handleStartDateChange}
    />
    <input
      type="date"
      bind:value={endDate}
      aria-label="Select End Date"
      on:input={handleEndDateChange}
    />
  {:else if mode === 'time'}
    <input
      type="time"
      bind:value={time}
      aria-label="Select Time"
      on:input={handleTimeChange}
    />
  {/if}
</div>

<style lang="css">
  @import './DatePicker.css';
</style>

// pkgs/experimental/swarmakit/libs/vue/src/components/DatePicker/DatePicker.vue
<template>
  <div class="date-picker-container">
    <input 
      type="date" 
      :value="startDate" 
      :disabled="disabled" 
      @input="updateStartDate" 
      aria-label="Start Date"
      :aria-disabled="disabled"
    />
    <input 
      v-if="isDateRange" 
      type="date" 
      :value="endDate" 
      :disabled="disabled" 
      @input="updateEndDate" 
      aria-label="End Date"
      :aria-disabled="disabled"
    />
    <input 
      v-if="isTimePicker" 
      type="time" 
      :value="selectedTime" 
      :disabled="disabled" 
      @input="updateTime" 
      aria-label="Time Picker"
      :aria-disabled="disabled"
    />
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'DatePicker',
  props: {
    startDate: {
      type: String,
      default: '',
    },
    endDate: {
      type: String,
      default: '',
    },
    selectedTime: {
      type: String,
      default: '',
    },
    isDateRange: {
      type: Boolean,
      default: false,
    },
    isTimePicker: {
      type: Boolean,
      default: false,
    },
    disabled: {
      type: Boolean,
      default: false,
    },
  },
  methods: {
    updateStartDate(event: Event) {
      const input = event.target as HTMLInputElement;
      this.$emit('update:startDate', input.value);
    },
    updateEndDate(event: Event) {
      const input = event.target as HTMLInputElement;
      this.$emit('update:endDate', input.value);
    },
    updateTime(event: Event) {
      const input = event.target as HTMLInputElement;
      this.$emit('update:selectedTime', input.value);
    },
  },
});
</script>

<style scoped lang="css">
@import './DatePicker.css';
</style>
