// pkgs/experimental/swarmakit/libs/vue/src/components/Captcha/Captcha.vue
<template>
  <div class="captcha-container">
    <div class="captcha" :class="{ 'captcha--error': hasError, 'captcha--solved': isSolved }">
      <span v-if="!isSolved">{{ captchaText }}</span>
      <span v-else>✔ Solved</span>
    </div>
    <button @click="solveCaptcha" :disabled="isSolved" aria-label="solve captcha">Solve</button>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';

export default defineComponent({
  name: 'Captcha',
  props: {
    captchaText: {
      type: String,
      default: 'Please solve the captcha',
    },
  },
  setup(props) {
    const isSolved = ref(false);
    const hasError = ref(false);

    const solveCaptcha = () => {
      if (props.captchaText === 'Please solve the captcha') {
        isSolved.value = true;
        hasError.value = false;
      } else {
        hasError.value = true;
      }
    };

    return {
      isSolved,
      hasError,
      solveCaptcha,
    };
  },
});
</script>

<style scoped lang="css">
@import './Captcha.css';
</style>

// pkgs/experimental/swarmakit/libs/svelte/src/components/Captcha/Captcha.svelte
<script lang="ts">
  export let question: string;
  export let onSolve: (answer: string) => void;
  export let errorMessage: string = '';
  export let solved: boolean = false;

  let userAnswer: string = '';

  function handleSubmit() {
    onSolve(userAnswer);
  }
</script>

<div class="captcha-container">
  <p>{question}</p>
  <input
    type="text"
    bind:value={userAnswer}
    placeholder="Type your answer"
    aria-label="Captcha input"
    aria-invalid={errorMessage ? 'true' : 'false'}
  />
  <button on:click={handleSubmit} disabled={solved}>Submit</button>
  {#if errorMessage}
    <p class="error-message" role="alert">{errorMessage}</p>
  {/if}
  {#if solved}
    <p class="solved-message">Captcha Solved!</p>
  {/if}
</div>

<style lang="css">
  @import './Captcha.css';
</style>
