// pkgs/experimental/swarmakit/libs/sveltekit/src/components/Checkbox/Checkbox.svelte
<script lang="ts">
  export let label: string;
  export let checked: boolean = false;
  export let disabled: boolean = false;

  function toggleCheck() {
    if (!disabled) {
      checked = !checked;
    }
  }
</script>

<div class="checkbox-container">
  <input
    type="checkbox"
    bind:checked
    disabled={disabled}
    id="checkbox"
    aria-checked={checked}
    aria-disabled={disabled}
    on:change={toggleCheck}
  />
  <label for="checkbox">{label}</label>
</div>

<style lang="css">
  @import './Checkbox.css';
</style>

// pkgs/experimental/swarmakit/libs/vue/src/components/Checkbox/Checkbox.vue
<template>
  <div class="checkbox-container">
    <input 
      type="checkbox" 
      :checked="checked" 
      :disabled="disabled" 
      @change="$emit('update:checked', ($event.target as HTMLInputElement).checked)" 
      :aria-checked="checked" 
      :aria-disabled="disabled"
    />
    <label :class="{ 'checkbox--disabled': disabled }">
      <slot />
    </label>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'Checkbox',
  props: {
    checked: {
      type: Boolean,
      default: false,
    },
    disabled: {
      type: Boolean,
      default: false,
    },
  },
});
</script>

<style scoped lang="css">
@import './Checkbox.css';
</style>
