// pkgs/experimental/swarmakit/libs/vue/src/components/Button/Button.vue
<template>
  <button
    :class="['button', buttonType, { disabled }]"
    :aria-disabled="disabled"
    :disabled="disabled"
    @mouseover="isHover = true"
    @mouseleave="isHover = false"
    @mousedown="isActive = true"
    @mouseup="isActive = false"
  >
    <slot></slot>
  </button>
</template>

<script lang="ts">
import { defineComponent, ref, computed } from 'vue';

export default defineComponent({
  name: 'Button',
  props: {
    type: {
      type: String as () => 'primary' | 'secondary',
      default: 'primary',
    },
    disabled: {
      type: Boolean,
      default: false,
    },
  },
  setup(props) {
    const isHover = ref(false);
    const isActive = ref(false);

    const buttonType = computed(() => {
      if (props.disabled) return 'disabled';
      if (isActive.value) return 'active';
      if (isHover.value) return 'hover';
      return props.type;
    });

    return {
      isHover,
      isActive,
      buttonType,
    };
  },
});
</script>

<style scoped>
@import './Button.css';
</style>

// pkgs/experimental/swarmakit/libs/sveltekit/src/components/Button/Button.svelte
<script lang="ts">
  export let label: string;
  export let type: 'primary' | 'secondary' = 'primary';
  export let disabled: boolean = false;
  export let ariaLabel: string;
  export let onClick: () => void;
</script>

<button
  class={`button ${type}`}
  on:click={onClick}
  disabled={disabled}
  aria-label={ariaLabel}
>
  {label}
</button>

<style lang="css">
  @import './Button.css';
</style>
