// pkgs/experimental/swarmakit/libs/vue/src/components/ActivityIndicators/ActivityIndicators.vue
<template>
  <div :class="['activity-indicator', type]" role="status" aria-live="polite">
    <span v-if="type === 'loading'" class="spinner"></span>
    <span v-else>{{ message }}</span>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'ActivityIndicators',
  props: {
    type: {
      type: String as () => 'loading' | 'success' | 'error',
      default: 'loading',
      validator: (value: string) => ['loading', 'success', 'error'].includes(value),
    },
    message: {
      type: String,
      default: 'Loading...',
    },
  },
});
</script>

<style scoped>
@import './ActivityIndicators.css';
</style>

// pkgs/experimental/swarmakit/libs/svelte/src/components/ActivityIndicators/ActivityIndicators.svelte
<script lang="ts">
  export let state: 'loading' | 'success' | 'error' = 'loading';

  $: className = `activity-indicator ${state}`;
</script>

<div class={className} role="status" aria-live="polite">
  {#if state === 'loading'}
    <span>Loading...</span>
  {:else if state === 'success'}
    <span>Success!</span>
  {:else if state === 'error'}
    <span>Error occurred!</span>
  {/if}
</div>

<style lang="css">
  @import './ActivityIndicators.css';
</style>
