// pkgs/experimental/swarmakit/libs/svelte/src/components/CollapsibleMenuList/CollapsibleMenuList.svelte
<script lang="ts">
  export let items: { id: number; label: string; expanded?: boolean; active?: boolean }[] = [];

  const toggleExpand = (item: { id: number; label: string; expanded?: boolean; active?: boolean }) => {
    item.expanded = !item.expanded;
  };

  const setActive = (item: { id: number; label: string; expanded?: boolean; active?: boolean }) => {
    items.forEach(i => i.active = false);
    item.active = true;
  };
</script>

<ul class="collapsible-menu">
  {#each items as item (item.id)}
    <li 
      class="menu-item {item.expanded ? 'expanded' : 'collapsed'} {item.active ? 'active' : ''}"
      on:click={() => setActive(item)}
      on:mouseenter={() => item.expanded = true}
      on:mouseleave={() => item.expanded = false}
      role="menuitem"
      on:keydown={(e) => {
        if (e.key === 'Enter' || e.key === ' ') {
          setActive(item);
          e.preventDefault(); // Prevent scrolling when space is pressed
        }
      }}
    >
      <div class="menu-label" on:click={() => toggleExpand(item)} role="button" tabindex='0' on:keydown={(e)=> {if (e.key === 'Enter' || e.key === ''){
        toggleExpand(item);
        e.preventDefault();
      }}}>
        {item.label}
      </div>
      {#if item.expanded}
        <ul class="submenu">
          <li>Sub-item 1</li>
          <li>Sub-item 2</li>
          <li>Sub-item 3</li>
        </ul>
      {/if}
    </li>
  {/each}
</ul>

<style lang="css">
  @import './CollapsibleMenuList.css';
</style>

// pkgs/experimental/swarmakit/libs/vue/src/components/CollapsibleMenuList/CollapsibleMenuList.vue
<template>
  <ul class="collapsible-menu-list" role="menu">
    <li
      v-for="(item, index) in items"
      :key="index"
      class="menu-item"
      :class="{ expanded: item.expanded, active: item.active }"
      @mouseenter="hoverItem(index)"
      @mouseleave="unhoverItem(index)"
    >
      <button
        class="menu-button"
        :aria-expanded="item.expanded"
        @click="toggleExpand(index)"
      >
        {{ item.label }}
      </button>
      <ul v-if="item.expanded" class="submenu" role="menu">
        <li v-for="(subItem, subIndex) in item.subItems" :key="subIndex" role="menuitem">
          {{ subItem }}
        </li>
      </ul>
    </li>
  </ul>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

interface MenuItem {
  label: string;
  expanded: boolean;
  active: boolean;
  subItems: string[];
}

export default defineComponent({
  name: 'CollapsibleMenuList',
  props: {
    items: {
      type: Array as () => MenuItem[],
      required: true,
    },
  },
  setup(props) {
    const toggleExpand = (index: number) => {
      props.items[index].expanded = !props.items[index].expanded;
    };

    const hoverItem = (index: number) => {
      props.items[index].active = true;
    };

    const unhoverItem = (index: number) => {
      props.items[index].active = false;
    };

    return { toggleExpand, hoverItem, unhoverItem };
  },
});
</script>

<style scoped lang="css">
.collapsible-menu-list {
  list-style: none;
  padding: 0;
  margin: 0;
}

.menu-item {
  margin-bottom: var(--menu-item-margin-bottom, 10px);
}

.menu-button {
  background: none;
  border: none;
  text-align: left;
  width: 100%;
  padding: var(--menu-button-padding, 10px);
  cursor: pointer;
}

.menu-item.expanded .menu-button {
  font-weight: var(--expanded-font-weight, bold);
}

.menu-item.active .menu-button {
  background-color: var(--active-background-color, #f0f0f0);
}

.submenu {
  list-style: none;
  padding-left: var(--submenu-padding-left, 20px);
  margin: 0;
}
</style>
