// pkgs/experimental/swarmakit/libs/sveltekit/src/components/RadioButton/RadioButton.svelte
<script lang="ts">
  export let selected: boolean = false;
  export let disabled: boolean = false;
  export let label: string = '';

  function handleSelect() {
    if (!disabled) {
      selected = !selected;
    }
  }
</script>

<div class="radio-button" role="radio" aria-checked={selected} aria-disabled={disabled} on:click={handleSelect} tabindex="0" on:keydown={(e)=>{if(e.key === "Enter" || e.key === ' ') {handleSelect}}}>
  <input
    id="radio-input"
    type="radio"
    checked={selected}
    disabled={disabled}
    aria-label={label}
  />
  <label for="radio-input">{label}</label>
</div>

<style lang="css">
  @import './RadioButton.css';
</style>

// pkgs/experimental/swarmakit/libs/vue/src/components/RadioButton/RadioButton.vue
<template>
  <div class="radio-button-container">
    <label :class="{ disabled: disabled }">
      <input 
        type="radio" 
        :checked="checked" 
        :disabled="disabled" 
        @change="onChange" 
        :aria-checked="checked" 
        :aria-disabled="disabled"
      />
      <span class="radio-label"><slot></slot></span>
    </label>
  </div>
</template>

<script lang="ts">
import { defineComponent, PropType } from 'vue';

export default defineComponent({
  name: 'RadioButton',
  props: {
    checked: {
      type: Boolean,
      default: false,
    },
    disabled: {
      type: Boolean,
      default: false,
    },
    value: {
      type: String as PropType<string>,
      required: true,
    },
    name: {
      type: String as PropType<string>,
      required: true,
    },
  },
  emits: ['update:checked'],
  methods: {
    onChange(event: Event) {
      if (!this.disabled) {
        this.$emit('update:checked', (event.target as HTMLInputElement).checked);
      }
    },
  },
});
</script>

<style scoped lang="css">
@import './RadioButton.css';
</style>
