// pkgs/experimental/swarmakit/libs/vue/src/components/AudioPlayer/AudioPlayer.vue
<template>
  <div class="audio-player" role="region" aria-label="Audio player">
    <audio ref="audioElement" :src="src" @loadeddata="onLoadedData"></audio>
    <button @click="togglePlay" class="control-button" aria-label="Play/Pause">
      {{ isPlaying ? 'Pause' : 'Play' }}
    </button>
    <button @click="toggleMute" class="control-button" aria-label="Mute/Unmute">
      {{ isMuted ? 'Unmute' : 'Mute' }}
    </button>
    <input
      type="range"
      class="volume-control"
      min="0"
      max="1"
      step="0.1"
      v-model="volume"
      @input="changeVolume"
      aria-label="Volume control"
    />
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';

export default defineComponent({
  name: 'AudioPlayer',
  props: {
    src: {
      type: String,
      required: true,
    },
  },
  setup() {
    const audioElement = ref<HTMLAudioElement | null>(null);
    const isPlaying = ref(false);
    const isMuted = ref(false);
    const volume = ref(1);

    const togglePlay = () => {
      const audio = audioElement.value;
      if (audio) {
        if (isPlaying.value) {
          audio.pause();
        } else {
          audio.play();
        }
        isPlaying.value = !isPlaying.value;
      }
    };

    const toggleMute = () => {
      const audio = audioElement.value;
      if (audio) {
        audio.muted = !audio.muted;
        isMuted.value = audio.muted;
      }
    };

    const changeVolume = () => {
      const audio = audioElement.value;
      if (audio) {
        audio.volume = volume.value;
      }
    };

    const onLoadedData = () => {
      const audio = audioElement.value;
      if (audio) {
        volume.value = audio.volume;
      }
    };

    return { isPlaying, isMuted, volume, togglePlay, toggleMute, changeVolume, onLoadedData };
  },
});
</script>

<style scoped lang="css">
.audio-player {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 10px;
  background-color: var(--player-bg-color);
  border-radius: 5px;
}

.control-button {
  background-color: var(--button-bg-color);
  color: var(--button-text-color);
  border: none;
  padding: 5px 10px;
  cursor: pointer;
  border-radius: 3px;
}

.volume-control {
  width: 100px;
}
</style>

// pkgs/experimental/swarmakit/libs/svelte/src/components/AudioPlayer/AudioPlayer.svelte
<script lang="ts">
  import { onMount } from 'svelte';

  export let src: string = '';
  export let isPlaying: boolean = false;
  export let isMuted: boolean = false;
  export let volume: number = 1;

  let audioElement: HTMLAudioElement;

  const togglePlay = () => {
    if (isPlaying) {
      audioElement.pause();
    } else {
      audioElement.play();
    }
    isPlaying = !isPlaying;
  };

  const toggleMute = () => {
    audioElement.muted = isMuted = !isMuted;
  };

  const handleVolumeChange = (event: Event) => {
    const target = event.target as HTMLInputElement;
    volume = parseFloat(target.value);
    audioElement.volume = volume;
  };

  onMount(() => {
    audioElement.volume = volume;
  });
</script>

<div class="audio-player" role="region" aria-label="Audio Player">
  <audio bind:this={audioElement} src={src}></audio>
  <button on:click={togglePlay} on:keydown={(e) => e.key === 'Enter' && togglePlay()} aria-label={isPlaying ? 'Pause' : 'Play'}>
    {#if isPlaying}Pause{:else}Play{/if}
  </button>
  <button on:click={toggleMute} on:keydown={(e) => e.key === 'Enter' && toggleMute()} aria-label={isMuted ? 'Unmute' : 'Mute'}>
    {#if isMuted}Unmute{:else}Mute{/if}
  </button>
  <input type="range" min="0" max="1" step="0.01" value={volume} on:input={handleVolumeChange} aria-label="Volume Control" />
</div>

<style lang="css">
  @import './AudioPlayer.css';
</style>
