// pkgs/experimental/swarmakit/libs/svelte/src/components/NumberInputWithIncrement/NumberInputWithIncrement.svelte
<script lang="ts">
  export let value: number = 0;
  export let min: number = -Infinity;
  export let max: number = Infinity;
  export let step: number = 1;
  export let disabled: boolean = false;

  function increment() {
    if (!disabled && value < max) {
      value += step;
    }
  }

  function decrement() {
    if (!disabled && value > min) {
      value -= step;
    }
  }
</script>

<div class="number-input" aria-label="Number Input with Increment">
  <button class="decrement" on:click={decrement} disabled={disabled || value <= min} aria-label="Decrement">-</button>
  <input
    type="number"
    bind:value
    min={min}
    max={max}
    step={step}
    disabled={disabled}
    aria-disabled={disabled}
    aria-valuemin={min}
    aria-valuemax={max}
    aria-valuenow={value}
  />
  <button class="increment" on:click={increment} disabled={disabled || value >= max} aria-label="Increment">+</button>
</div>

<style lang="css">
  @import './NumberInputWithIncrement.css';
</style>

// pkgs/experimental/swarmakit/libs/vue/src/components/NumberInputWithIncrement/NumberInputWithIncrement.vue
<template>
  <div class="number-input-container">
    <button 
      class="decrement-button" 
      @click="decrement" 
      :disabled="disabled" 
      aria-label="Decrement"
    >
      -
    </button>
    <input 
      type="number" 
      v-model="currentValue" 
      :disabled="disabled" 
      aria-label="Number Input"
    />
    <button 
      class="increment-button" 
      @click="increment" 
      :disabled="disabled" 
      aria-label="Increment"
    >
      +
    </button>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref} from 'vue';

export default defineComponent({
  name: 'NumberInputWithIncrement',
  props: {
    modelValue: {
      type: Number,
      default: 0,
    },
    step: {
      type: Number,
      default: 1,
    },
    disabled: {
      type: Boolean,
      default: false,
    },
  },
  emits: ['update:modelValue'],
  setup(props, { emit }) {
    const currentValue = ref(props.modelValue);

    const increment = () => {
      currentValue.value += props.step;
      emit('update:modelValue', currentValue.value);
    };

    const decrement = () => {
      currentValue.value -= props.step;
      emit('update:modelValue', currentValue.value);
    };

    return { currentValue, increment, decrement };
  },
});
</script>

<style scoped lang="css">
@import './NumberInputWithIncrement.css';
</style>
