// pkgs/experimental/swarmakit/libs/sveltekit/src/components/PinnedList/PinnedList.svelte
<script lang="ts">
  type ListItem = {
    id: number;
    text: string;
    pinned: boolean;
  };

  export let items: ListItem[] = [];
  export let selectedItem: number | null = null;

  const togglePin = (id: number) => {
    items = items.map(item => item.id === id ? { ...item, pinned: !item.pinned } : item);
  };

  const selectItem = (id: number) => {
    selectedItem = id;
  };
</script>

<ul class="pinned-list" role="list">
  {#each items as item (item.id)}
    <li
      class="list-item {item.pinned ? 'pinned' : ''} {selectedItem === item.id ? 'selected' : ''}"
      on:click={() => selectItem(item.id)}
      on:keydown={(e)=>{if(e.key === 'Enter' || e.key === ' '){selectItem(item.id)}}}
      aria-selected={selectedItem === item.id}
      tabindex ="0"
      role="tab"
    >
      <span class="item-text">{item.text}</span>
      <button
        class="pin-button"
        on:click|stopPropagation={() => togglePin(item.id)}
        aria-label={item.pinned ? 'Unpin item' : 'Pin item'}
      >
        {item.pinned ? '📌' : '📍'}
      </button>
    </li>
  {/each}
</ul>

<style lang="css">
  @import './PinnedList.css';
</style>

// pkgs/experimental/swarmakit/libs/vue/src/components/PinnedList/PinnedList.vue
<template>
  <ul class="pinned-list">
    <li
      v-for="item in items"
      :key="item.id"
      :class="[
        'pinned-list-item',
        { pinned: item.pinned, selected: item.id === selectedItem, hover: item.id === hoveredItem }
      ]"
      @click="selectItem(item.id)"
      @mouseover="hoveredItem = item.id"
      @mouseleave="hoveredItem = null"
      :aria-selected="item.id === selectedItem ? 'true' : 'false'"
    >
      {{ item.label }}
    </li>
  </ul>
</template>

<script lang="ts">
import { defineComponent, ref} from 'vue';

interface ListItem {
  id: number;
  label: string;
  pinned: boolean;
}

export default defineComponent({
  name: 'PinnedList',
  props: {
    items: {
      type: Array as () => ListItem[],
      required: true,
    },
    selectedItem: {
      type: Number,
      required: true,
    },
  },
  setup(_, { emit }) {
    const hoveredItem = ref<number | null>(null);

    const selectItem = (id: number) => {
      emit('update:selectedItem', id);
    };

    return { hoveredItem, selectItem };
  },
});
</script>

<style scoped lang="css">
.pinned-list {
  list-style: none;
  padding: 0;
  margin: 0;
}

.pinned-list-item {
  padding: var(--list-item-padding, 10px 15px);
  margin: 4px 0;
  cursor: pointer;
  transition: background-color 0.2s;
  border-radius: var(--list-border-radius, 4px);
}

.pinned-list-item.pinned {
  background-color: var(--pinned-bg, #ffc107);
}

.pinned-list-item.selected {
  background-color: var(--selected-bg, #007bff);
  color: var(--selected-color, #fff);
}

.pinned-list-item.hover:not(.selected) {
  background-color: var(--hover-bg, #e9ecef);
}
</style>
