// pkgs/experimental/swarmakit/libs/svelte/src/components/ValidationMessages/ValidationMessages.svelte
<script lang="ts">
  export let message: string = '';
  export let type: 'success' | 'error' | 'warning' = 'success';

  $: className = `validation-message ${type}`;
</script>

<div class={className} role="alert" aria-live="polite">
  {message}
</div>

<style lang="css">
  @import './ValidationMessages.css';
</style>

// pkgs/experimental/swarmakit/libs/vue/src/components/ValidationMessages/ValidationMessages.vue
<template>
  <div :class="['validation-message', type]" role="alert" aria-live="assertive">
    <slot />
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'ValidationMessages',
  props: {
    type: {
      type: String as () => 'success' | 'error' | 'warning',
      default: 'success',
      validator: (value: string) => ['success', 'error', 'warning'].includes(value),
    },
  },
});
</script>

<style scoped>
@import './ValidationMessages.css';
</style>
