// pkgs/experimental/swarmakit/libs/sveltekit/src/components/Textarea/Textarea.svelte
<script lang="ts">
  export let value: string = '';
  export let disabled: boolean = false;

  function handleInput(event: Event) {
    value = (event.target as HTMLTextAreaElement).value;
  }
</script>

<textarea
  class="textarea"
  bind:value={value}
  on:input={handleInput}
  disabled={disabled}
  aria-label="Textarea"
></textarea>

<style lang="css">
  @import './Textarea.css';
</style>

// pkgs/experimental/swarmakit/libs/vue/src/components/Textarea/Textarea.vue
<template>
  <div class="textarea-container">
    <textarea 
      :placeholder="placeholder" 
      :disabled="disabled"
      aria-label="Textarea input"
      v-model="text"
      @input="onInput"
    ></textarea>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';

export default defineComponent({
  name: 'Textarea',
  props: {
    placeholder: {
      type: String,
      default: 'Enter text...',
    },
    disabled: {
      type: Boolean,
      default: false,
    },
  },
  emits: ['input'],
  setup(_, { emit }) {
    const text = ref('');

    const onInput = () => {
      emit('input', text.value);
    };

    return {
      text,
      onInput,
    };
  },
});
</script>

<style scoped>
@import './Textarea.css';
</style>
