// pkgs/experimental/swarmakit/libs/sveltekit/src/components/PasswordConfirmationField/PasswordConfirmationField.svelte
<script lang="ts">
  export let password: string = '';
  export let confirmPassword: string = '';
  export let disabled: boolean = false;

  let passwordsMatch: boolean = true;

  $: passwordsMatch = password === confirmPassword;
</script>

<div class="password-confirmation-field" aria-label="Password Confirmation Field">
  <input
    type="password"
    bind:value={password}
    placeholder="Enter password"
    disabled={disabled}
    aria-disabled={disabled}
    aria-label="Password"
  />
  <input
    type="password"
    bind:value={confirmPassword}
    placeholder="Confirm password"
    disabled={disabled}
    aria-disabled={disabled}
    aria-label="Confirm Password"
  />
  {#if !passwordsMatch}
    <p class="error" aria-live="assertive">Passwords do not match</p>
  {/if}
</div>

<style lang="css">
  @import './PasswordConfirmationField.css';
</style>

// pkgs/experimental/swarmakit/libs/vue/src/components/PasswordConfirmationField/PasswordConfirmationField.vue
<template>
  <div class="password-confirmation-container">
    <input 
      type="password" 
      v-model="password" 
      :disabled="disabled" 
      placeholder="Enter password" 
      aria-label="Enter password"
    />
    <input 
      type="password" 
      v-model="confirmPassword" 
      :disabled="disabled" 
      placeholder="Confirm password" 
      aria-label="Confirm password"
    />
    <p :class="{'match': isMatching, 'not-match': !isMatching}">
      {{ isMatching ? 'Passwords match' : 'Passwords do not match' }}
    </p>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, computed } from 'vue';

export default defineComponent({
  name: 'PasswordConfirmationField',
  props: {
    disabled: {
      type: Boolean,
      default: false,
    },
  },
  setup() {
    const password = ref('');
    const confirmPassword = ref('');
    
    const isMatching = computed(() => password.value === confirmPassword.value);

    return { password, confirmPassword, isMatching };
  },
});
</script>

<style scoped lang="css">
@import './PasswordConfirmationField.css';
</style>
