// pkgs/experimental/swarmakit/libs/vue/src/components/SearchInputWithFilterOptions/SearchInputWithFilterOptions.vue
<template>
  <div class="search-container">
    <input 
      type="text" 
      :placeholder="placeholder" 
      :disabled="disabled"
      aria-label="Search input"
      v-model="query"
      @input="onInput"
    />
    <button 
      :aria-pressed="filtersActive" 
      @click="toggleFilters"
    >
      Filters
    </button>
    <div v-if="filtersActive" class="filter-options">
      <slot name="filters"></slot>
    </div>
    <div v-if="noResults" class="no-results">
      No Results Found
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';

export default defineComponent({
  name: 'SearchInputWithFilterOptions',
  props: {
    placeholder: {
      type: String,
      default: 'Search...',
    },
    disabled: {
      type: Boolean,
      default: false,
    },
    filtersActive: {
      type: Boolean,
      default: false,
    },
    noResults: {
      type: Boolean,
      default: false,
    },
  },
  emits: ['update:filtersActive', 'input'],
  setup(props, { emit }) {
    const query = ref('');

    const onInput = () => {
      emit('input', query.value);
    };

    const toggleFilters = () => {
      emit('update:filtersActive', !props.filtersActive);
    };

    return {
      query,
      onInput,
      toggleFilters,
    };
  },
});
</script>

<style scoped>
@import './SearchInputWithFilterOptions.css';
</style>

// pkgs/experimental/swarmakit/libs/sveltekit/src/components/SearchInputWithFilterOptions/SearchInputWithFilterOptions.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';

  export let query: string = '';
  export let filters: string[] = [];
  export let activeFilters: string[] = [];
  export let disabled: boolean = false;

  const dispatch = createEventDispatcher();

  function updateQuery(event: Event) {
    query = (event.target as HTMLInputElement).value;
    dispatch('search', { query });
  }

  function toggleFilter(filter: string) {
    if (activeFilters.includes(filter)) {
      activeFilters = activeFilters.filter(f => f !== filter);
    } else {
      activeFilters = [...activeFilters, filter];
    }
    dispatch('filterChange', { activeFilters });
  }
</script>

<div class="search-input-container">
  <input
    type="text"
    class="search-input"
    placeholder="Search..."
    bind:value={query}
    on:input={updateQuery}
    disabled={disabled}
    aria-label="Search input"
  />
  <div class="filter-options">
    {#each filters as filter}
      <button
        type="button"
        class="filter-button {activeFilters.includes(filter) ? 'active' : ''}"
        on:click={() => toggleFilter(filter)}
        aria-pressed={activeFilters.includes(filter)}
        disabled={disabled}
      >
        {filter}
      </button>
    {/each}
  </div>
</div>

<style lang="css">
  @import './SearchInputWithFilterOptions.css';
</style>
